// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:816721547929:web:1c5a7a90b88ea3c0be5e08',
    messagingSenderId: '816721547929',
    projectId: 'messaging-app-5a448',
    authDomain: 'messaging-app-5a448.firebaseapp.com',
    storageBucket: 'messaging-app-5a448.firebasestorage.app',
    measurementId: 'G-82Z9LP43DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:816721547929:android:98f40bcf509ed216be5e08',
    messagingSenderId: '816721547929',
    projectId: 'messaging-app-5a448',
    storageBucket: 'messaging-app-5a448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:816721547929:ios:0c392d17329aaa4ebe5e08',
    messagingSenderId: '816721547929',
    projectId: 'messaging-app-5a448',
    storageBucket: 'messaging-app-5a448.firebasestorage.app',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:816721547929:ios:0c392d17329aaa4ebe5e08',
    messagingSenderId: '816721547929',
    projectId: 'messaging-app-5a448',
    storageBucket: 'messaging-app-5a448.firebasestorage.app',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:816721547929:web:1c5a7a90b88ea3c0be5e08',
    messagingSenderId: '816721547929',
    projectId: 'messaging-app-5a448',
    authDomain: 'messaging-app-5a448.firebaseapp.com',
    storageBucket: 'messaging-app-5a448.firebasestorage.app',
    measurementId: 'G-82Z9LP43DC',
  );
}
